// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: inventory/food/inventory/common/v1alpha/messages.proto

package orders_common_v1alpha

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NutritionalData nutrition data for a Product
type NutritionalData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Id uuid4 identifier of the nutritional data
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Calories number of calories in the product in grams
	Calories float32 `protobuf:"fixed32,2,opt,name=calories,proto3" json:"calories,omitempty"`
	// Carbs number of carbs in the product in grams
	Carbs float32 `protobuf:"fixed32,3,opt,name=carbs,proto3" json:"carbs,omitempty"`
	// Fat amount of fat in the product in grams
	Fat float32 `protobuf:"fixed32,4,opt,name=fat,proto3" json:"fat,omitempty"`
	// Protein amount of protein in grams
	Protein float32 `protobuf:"fixed32,5,opt,name=protein,proto3" json:"protein,omitempty"`
	// Sodium amount of sodium in grams
	Sodium float32 `protobuf:"fixed32,6,opt,name=sodium,proto3" json:"sodium,omitempty"`
}

func (x *NutritionalData) Reset() {
	*x = NutritionalData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_food_inventory_common_v1alpha_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NutritionalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NutritionalData) ProtoMessage() {}

func (x *NutritionalData) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_food_inventory_common_v1alpha_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NutritionalData.ProtoReflect.Descriptor instead.
func (*NutritionalData) Descriptor() ([]byte, []int) {
	return file_inventory_food_inventory_common_v1alpha_messages_proto_rawDescGZIP(), []int{0}
}

func (x *NutritionalData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NutritionalData) GetCalories() float32 {
	if x != nil {
		return x.Calories
	}
	return 0
}

func (x *NutritionalData) GetCarbs() float32 {
	if x != nil {
		return x.Carbs
	}
	return 0
}

func (x *NutritionalData) GetFat() float32 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *NutritionalData) GetProtein() float32 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *NutritionalData) GetSodium() float32 {
	if x != nil {
		return x.Sodium
	}
	return 0
}

// Product items the Food Bank stocks. Ex apples, bananas, chicken would be considered products
type Product struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image           [][]byte         `protobuf:"bytes,2,rep,name=image,proto3" json:"image,omitempty"`
	Name            string           `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NutritionalData *NutritionalData `protobuf:"bytes,4,opt,name=nutritional_data,json=nutritionalData,proto3" json:"nutritional_data,omitempty"`
	Tags            []string         `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *Product) Reset() {
	*x = Product{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_food_inventory_common_v1alpha_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_food_inventory_common_v1alpha_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_inventory_food_inventory_common_v1alpha_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetImage() [][]byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetNutritionalData() *NutritionalData {
	if x != nil {
		return x.NutritionalData
	}
	return nil
}

func (x *Product) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId   string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	OrderId     string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DeliveredAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	ExpireAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_food_inventory_common_v1alpha_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_food_inventory_common_v1alpha_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_inventory_food_inventory_common_v1alpha_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Item) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Item) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

func (x *Item) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

type AggregateInventoryData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Product  *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Quantity int32    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Items    []*Item  `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *AggregateInventoryData) Reset() {
	*x = AggregateInventoryData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inventory_food_inventory_common_v1alpha_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggregateInventoryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateInventoryData) ProtoMessage() {}

func (x *AggregateInventoryData) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_food_inventory_common_v1alpha_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateInventoryData.ProtoReflect.Descriptor instead.
func (*AggregateInventoryData) Descriptor() ([]byte, []int) {
	return file_inventory_food_inventory_common_v1alpha_messages_proto_rawDescGZIP(), []int{3}
}

func (x *AggregateInventoryData) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *AggregateInventoryData) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AggregateInventoryData) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_inventory_food_inventory_common_v1alpha_messages_proto protoreflect.FileDescriptor

var file_inventory_food_inventory_common_v1alpha_messages_proto_rawDesc = []byte{
	0x0a, 0x36, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x66, 0x6f, 0x6f, 0x64,
	0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x69,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x97, 0x01, 0x0a, 0x0f, 0x4e, 0x75, 0x74,
	0x72, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x61, 0x6c, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08,
	0x63, 0x61, 0x6c, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x62,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x63, 0x61, 0x72, 0x62, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x66, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x66, 0x61, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f,
	0x64, 0x69, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x73, 0x6f, 0x64, 0x69,
	0x75, 0x6d, 0x22, 0xb2, 0x01, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x59, 0x0a, 0x10, 0x6e, 0x75, 0x74, 0x72,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x2e, 0x4e, 0x75, 0x74, 0x72, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x0f, 0x6e, 0x75, 0x74, 0x72, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0xc8, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x0c, 0x64, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x64, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x41, 0x74, 0x12, 0x37, 0x0a, 0x09, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x41, 0x74, 0x22, 0xb1, 0x01, 0x0a, 0x16, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65,
	0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x40, 0x0a,
	0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26,
	0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x39, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x66, 0x6f, 0x6f,
	0x64, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x59, 0x5a, 0x57, 0x48, 0x61, 0x63, 0x6b, 0x44, 0x61,
	0x76, 0x69, 0x73, 0x46, 0x6f, 0x6f, 0x64, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x70, 0x62, 0x2f, 0x66, 0x6f,
	0x6f, 0x64, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x3b, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inventory_food_inventory_common_v1alpha_messages_proto_rawDescOnce sync.Once
	file_inventory_food_inventory_common_v1alpha_messages_proto_rawDescData = file_inventory_food_inventory_common_v1alpha_messages_proto_rawDesc
)

func file_inventory_food_inventory_common_v1alpha_messages_proto_rawDescGZIP() []byte {
	file_inventory_food_inventory_common_v1alpha_messages_proto_rawDescOnce.Do(func() {
		file_inventory_food_inventory_common_v1alpha_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_inventory_food_inventory_common_v1alpha_messages_proto_rawDescData)
	})
	return file_inventory_food_inventory_common_v1alpha_messages_proto_rawDescData
}

var file_inventory_food_inventory_common_v1alpha_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_inventory_food_inventory_common_v1alpha_messages_proto_goTypes = []interface{}{
	(*NutritionalData)(nil),        // 0: food.inventory.common.v1alpha.NutritionalData
	(*Product)(nil),                // 1: food.inventory.common.v1alpha.Product
	(*Item)(nil),                   // 2: food.inventory.common.v1alpha.Item
	(*AggregateInventoryData)(nil), // 3: food.inventory.common.v1alpha.AggregateInventoryData
	(*timestamppb.Timestamp)(nil),  // 4: google.protobuf.Timestamp
}
var file_inventory_food_inventory_common_v1alpha_messages_proto_depIdxs = []int32{
	0, // 0: food.inventory.common.v1alpha.Product.nutritional_data:type_name -> food.inventory.common.v1alpha.NutritionalData
	4, // 1: food.inventory.common.v1alpha.Item.delivered_at:type_name -> google.protobuf.Timestamp
	4, // 2: food.inventory.common.v1alpha.Item.expire_at:type_name -> google.protobuf.Timestamp
	1, // 3: food.inventory.common.v1alpha.AggregateInventoryData.product:type_name -> food.inventory.common.v1alpha.Product
	2, // 4: food.inventory.common.v1alpha.AggregateInventoryData.items:type_name -> food.inventory.common.v1alpha.Item
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_inventory_food_inventory_common_v1alpha_messages_proto_init() }
func file_inventory_food_inventory_common_v1alpha_messages_proto_init() {
	if File_inventory_food_inventory_common_v1alpha_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inventory_food_inventory_common_v1alpha_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NutritionalData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_food_inventory_common_v1alpha_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Product); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_food_inventory_common_v1alpha_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inventory_food_inventory_common_v1alpha_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggregateInventoryData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inventory_food_inventory_common_v1alpha_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inventory_food_inventory_common_v1alpha_messages_proto_goTypes,
		DependencyIndexes: file_inventory_food_inventory_common_v1alpha_messages_proto_depIdxs,
		MessageInfos:      file_inventory_food_inventory_common_v1alpha_messages_proto_msgTypes,
	}.Build()
	File_inventory_food_inventory_common_v1alpha_messages_proto = out.File
	file_inventory_food_inventory_common_v1alpha_messages_proto_rawDesc = nil
	file_inventory_food_inventory_common_v1alpha_messages_proto_goTypes = nil
	file_inventory_food_inventory_common_v1alpha_messages_proto_depIdxs = nil
}
